language: node_js
sudo: false
node_js:
  - "0.11"
  - "0.10"
cache: false
install:
  - npm install
  - gulp
  - sh ./scripts/run-kontrol.sh
before_script:
  - sleep 10
  - curl http://0.0.0.0:4000/kite
